baseURL: "https://fmaced1.github.io/"
title: fmaced1
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

#googleAnalytics: "G-TBW4WDGVWV"

minify:
    disableXML: true
    # minifyOutput: true

defaultContentLanguage: pt
languages:
  en:
    weight: 1
  pt:
    weight: 2
    languageCode: pt-br

languages:
    pt:
        languageName: "Blog"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: /archives/
                  weight: 5
                - name: Search
                  url: /search/
                  weight: 10
                - name: Tags
                  url: /tags/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: prod
    description: "Description"
    author: fmaced1
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Bem vindo! \U0001F44B"
        Content: >
            - Blog mantido por Fabricio Macedo **@fmaced1**, com a finalidade de compartilhar
            dicas, anotações e ferramentas relacionadas a cultura DevOps e desenvolvimento de software.

    socialIcons:
        - name: github
          url: "https://github.com/fmaced1/"
        - name: linkedin
          url: "https://www.linkedin.com/in/fmaced1/"

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true